
name: ruby_test
version: 0.0.1
language: ruby
description: Run test use `bundle exec rake`
public: true
tags:
  - ruby
  - test
inputs:
  - name: FLOW_ENABLE_FAILURE
    editable: true
    options:
      - TRUE
      - FALSE
outputs:
script_path: ./run.sh  
  
template: |  
  
  